### ISSUE TITLE
Ikea Rollos:  found unknown property with key 8

### ISSUE THREAD

**Issue by haarchri** [AlCalzone/ioBroker.tradfri#715] opened 2022-01-03 09:51 UTC
see since 3.0.x upgrade the following message in log:

```
tradfri.0 | 2022-01-03 10:49:21.538 | warn | (13574) object was: {"0":"IKEA of Sweden","1":"FYRTUR block-out roller blind","2":"","3":"2.3.073","6":3,"7":4487,"8":0,"9":94}
-- | -- | -- | --
tradfri.0 | 2022-01-03 10:49:21.537 | warn | (13574) found unknown property with key 8

```

**Comment by AlCalzone** [comment] 2022-01-03 11:49
Duplicate of #704

**Comment by AlCalzone** [comment] 2022-01-03 11:49
Please update to 3.1.0

**Closed by AlCalzone** 2022-01-03 11:49 UTC
